# Generated by Django 2.2.7 on 2020-07-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommend', '0003_auto_20200716_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resulttable',
            name='id',
        ),
        migrations.AlterField(
            model_name='resulttable',
            name='userId',
            field=models.IntegerField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
